name: "Origami &mdash; Design Prototyping"
description: "Design prototyping with Quartz Composer"

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments
collections:
  documentation:
    output: true

navigation:
- text: Examples
  url: /examples
- text: Tutorials
  url: /tutorials
- text: Documentation
  url: /documentation
- text: Community
  url: https://www.facebook.com/groups/origami.community/
  target: _blank
