name: "Origami &mdash; Design Prototyping"
description: "Design prototyping with Quartz Composer"

paginate: 10

baseurl: /origami

markdown: rdiscount
highlighter: pygments
collections:
  documentation:
    output: true

gems: [jekyll-paginate]